import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Gesture Prediction</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="main__display">
          <div className="main__card">
            <div className="main_text">
              <h4>Predicted Gesture</h4>
              <p>Nothing</p>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
